docs_dir: docs-src
site_dir: docs
site_name: RediSearch-PHP
repo_url: https://github.com/ethanhann/redisearch-php
site_author: Ethan Hann
copyright: © 2017 - Ethan Hann

pages:
- Getting Started: 'index.md'
- 'indexing.md'
- 'searching.md'
- 'suggesting.md'
- 'changelog.md'

extra_css:
    - css/style.css

theme:
  name: 'material'
  favicon: 'images/logo.png'
  logo: 'images/logo.png'
  palette:
    primary: 'red'
    accent: 'red'
  feature:
    tabs: false
